config/routes.rb
Rails.application.routes.draw do

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'=> "homes#about", as:'about'
    resources :items, only: [:show, :index]
    resources :customers, only: [:show, :edit, :update]
    get "public/customers" => "customers#unsubscribe"
    patch "public/customers" => "customers#unsubscribe_process"
    resources :cart_items, only: [:create, :index, :update, :destroy]
    delete 'cart_items' => 'cart_items#destroy_all'
    resources :orders, only: [:new, :create, :show, :index]
    post 'public/orders' => 'orders#infor', as:'infor'
    get 'public/orders' => 'orders#completed', as:'completed'
    resources :addresses, only: [:create, :edit, :update, :index, :destroy]

  end

   namespace :admin do
     root to: 'homes#top'
    resources :items, only: [:new, :show, :create, :edit, :index, :update]
    resources :genres, only: [:create, :index, :update, :edit]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:update, :show]
    resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :customer
   belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

 def validate_into_cart
    cart_items = self.customer.cart_items
    if (amount) == nil
       return (false)
    elsif cart_items.any? {|cart_item| cart_item.item_id == (item_id)} == true
       return (false)
    else
      return (true)
    end
 end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items
  has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
  has_many :order_details
  validates :name, {presence: true}
  validates :introduction, {presence: true}

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :item_orders, dependent: :destroy
  belongs_to :customer

  enum payment: {
    "クレジットカード" => 0,
    "銀行振込" => 1,
  }
  enum order_status: {
    "入金待ち" => 0,
    "入金確認" => 1,
    "製作中" => 2,
    "発送準備中" => 3,
    "発送済み" => 4,
  }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
before_action :authenticate_admin!,only: [:create,:edit,:update,:index]

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      flash[:genre_created_error] = "ジャンル名を入力してください"
    redirect_to
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      render 'edit'
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!
end   

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]

  def show
    @item = Item.find(params[:id])
  end

  def index
    @search = Item.ransack(params[:q])
    @items = @search.result.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
      redirect_to admin_item_path(@item)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      redirect_to edit_admin_item_path(@item)
    end
  end

  private
  def item_params
    params.require(:item).permit(:introduction, :name, :image, :is_active, :price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

	def index
		@search = Order.ransack(params[:q])
    @orders = @search.result.page(params[:page]).per(10)
	end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

	def total(items_total_price)
	end

	def update
		@order = Order.find(params[:id])
  end

  private
	def order_params
		params.require(:order).permit(:status)
	end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/index.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">

      <h2>ジャンル追加・一覧画面</h2><br>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="row">
     <div class="col-xs-10 col-xs-offset-1">
    <h2>商品編集</h2>

    <% if @item.errors.any? %>
    <h3><%= @item.errors.count %>error occurrence</h3>
    <ul>
        <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
    <% end %>
    	<div class="field">
          	 <%= image_tag @item.get_image(80,80) %>
    	</div>
    </div>
    <div class="col-xs-7">
       <%= form_with(model: @item, url: admin_item_path, method: :patch, local: true) do |f| %>
            <div class="field">
            	<%= f.label :商品名 %>
            	<%= f.text_field :name, class: "form" %>
            </div>
            <div class="field">
            	<%= f.label :商品説明 %>
            	<%= f.text_area :introduction %>
            </div>

            <div class="field">
            	<%= f.label :税抜価格 %>
            	<%= f.text_field :price %>
            	円
            </div>

            <tr>
              <th>販売ステータス</th>
              <td><%= f.select :is_active, [["販売中","false"], ["販売不可","true"]], include_blank: "--選択してください--" %></td>
            </tr>

            <div class="text-right">
    		<%= f.submit "変更を保存", class:  "btn btn-primary text-right" %>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/items/index.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
<h2>商品一覧</h2>
<div class="text-right">
<%= link_to "新規登録", new_admin_item_path, class:"btn btn-lg btn-primary" %>
</div>

<table class="table">
	<thead>
		<tr>
			<th>商品一覧</th>
			<th>商品名</th>
			<th>税抜価格</th>
			<th>ステータス</th>
		</tr>
	</thead>
	<tbody>
		<% @items.each do |item| %>
			<tr>
				<th><%= item.id %></th>
　　　　　<td><%= link_to item.name ,admin_item_path(item) %></td>
				<th><%= item.price %></th	>
				<th><% if item.is_active == true %>
					販売中
					<% else %>
					販売停止中
					<% end %>
				</th>
			</tr>
		<% end %>
		 <%= paginate @items %>
	</tbody>
</table>
</div>
</div>

app/views/admin/items/new.html.erb
<div class="row">
    <h2>商品新規登録</h2>
    <%= form_with(model: @item, url: admin_items_path, method: :post, local: true) do |f| %>
    <% if @item.errors.any? %>
    <h3><%= @item.errors.count %>error occurrence</h3>
    <ul>
        <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
    <% end %>
        <div class="col-xs-5">
        	<div class="field">
        		<%= f.label :商品画像 %>
                 <%= f.file_field :image, accept: "image/*" %>
        	</div>
        </div>
        <div class="col-xs-7">
            <div class="field">
            	<%= f.label :商品名 %>
            	<%= f.text_field :name, class: "form" %>
            </div>
            <div class="field">
            	<%= f.label :商品説明 %>
            	<%= f.text_area :introduction %>
            </div>

            <div class="field">
            	<%= f.label :税抜価格 %>
            	<%= f.text_field :price %>円
            </div>
            <div class="field">
            	<%= f.radio_button :is_active, true %>
            	<%= f.label :is_active, "販売中" %>
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active, "売切れ" %>
            </div>
            <div class="actions row">
            <%= f.hidden_field :id, :value => @item.id %>
    		<%= f.submit "新規登録",class:"btn btn-primary col-xs-12" %>
            </div>
        </div>
    <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="row">
	<h2>商品詳細</h2>

	<div class="col-xs-5">
		 <%= image_tag @item.get_image(80,80) %>
	</div>
	<div class="col-xs-7">
		<table class="table">
			<tr>
				<th>商品名</th>
				<th><%= @item.name %></th>
			</tr>
			<tr>
				<th>商品説明</th>
				<th><%= @item.introduction %></th>
			</tr>
			<tr>
				<th>税込価格（税抜価格）</th>
				<th><%= (@item.price * 1.1).to_i %>(<%= @item.price %>)円</th>
			</tr>
		</table>
		<div>
		<%= link_to ' 編集する', edit_admin_item_path(@item), class: "btn btn-success glyphicon glyphicon-wrench pull-right" %>
	    </div>
	</div>
</div>

app/views/admin/orders/show.html.erb
<div class="row">
  <h2>注文履歴詳細</h2>
  <div style="margin-top: 50px;">
    <table class="table">
      <tbody>
        <tr>
          <th scope="row">購入者</th>
          <td><%=link_to @order.customer.first_name + @order.customer.last_name , admin_customer_path(@order.customer.id) %></td>
        </tr>
        <tr>
          <th scope="row">配送先</th>
          <td>
            <p><%= @order.postal_code %><%= @order.address %></p>
            <p><%= @order.receive_name %></p>
          </td>
        </tr>
        <tr>
          <th scope="row">支払方法</th>
          <td><%= @order.payment %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-xs-8"style="margin-top: 50px;">
    <table class="table table-bordered">
      <thead>
        <tr class="table-head" style="background-color:#F5F5F5;">
          <th scope="col">商品名</th>
          <th scope="col">単価（税込）</th>
          <th scope="col">数量</th>
          <th scope="col">小計</th>
        </tr>
      </thead>
    </table>
  </div>
  <div class="col-xs-4"style="margin-top: 120px;">
    <table class="table">
      <tbody>
        <tr>
          <th scope="row">商品合計</th>
          <td><%= @sum %></td>
        </tr>
        <tr>
          <th scope="row">送料</th>
          <td><%= @order.postage %></td>
        </tr>
        <tr>
          <th scope="row">請求金額合計</th>
          <td><%= @sum + @order.postage %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>