config/routes.rb
Rails.application.routes.draw do

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'=> "homes#about", as:'about'
    resources :items, only: [:show, :index]
    resources :customers, only: [:show, :edit, :update]
    get "public/customers" => "customers#unsubscribe"
    patch "public/customers" => "customers#unsubscribe_process"
    resources :cart_items, only: [:create, :index, :update, :destroy]
    delete 'cart_items' => 'cart_items#destroy_all'
    resources :orders, only: [:new, :create, :show, :index]
    post 'public/orders' => 'orders#infor', as:'infor'
    get 'public/orders' => 'orders#completed', as:'completed'
    resources :addresses, only: [:create, :edit, :update, :index, :destroy]

  end

   namespace :admin do
     root to: 'homes#top'
    resources :items, only: [:new, :show, :create, :edit, :index, :update]
    resources :genres, only: [:create, :index, :update, :edit]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:update, :show]
    resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :customer
   belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

 def validate_into_cart
    cart_items = self.customer.cart_items
    if (amount) == nil
       return (false)
    elsif cart_items.any? {|cart_item| cart_item.item_id == (item_id)} == true
       return (false)
    else
      return (true)
    end
 end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items
  has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
  has_many :order_details
  validates :name, {presence: true}
  validates :introduction, {presence: true}

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :item_orders, dependent: :destroy
  belongs_to :customer

  enum payment: {
    "クレジットカード" => 0,
    "銀行振込" => 1,
  }
  enum order_status: {
    "入金待ち" => 0,
    "入金確認" => 1,
    "製作中" => 2,
    "発送準備中" => 3,
    "発送済み" => 4,
  }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!
end   

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]

  def show
    @item = Item.find(params[:id])
  end

  def index
    @search = Item.ransack(params[:q])
    @items = @search.result.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
      redirect_to admin_item_path(@item)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      redirect_to edit_admin_item_path(@item)
    end
  end

  private
  def item_params
    params.require(:item).permit(:introduction, :name, :image, :is_active, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
       <a class="navbar-brand p-3" href="/"> LOGO
       </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
      aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">

     <% if customer_signed_in? %>
     <li class= "nav-item" >
  <span class= "customer-name  login-customer-name" >
    ようこそ、<%= current_customer.first_name %><%= current_customer.last_name %>さん！
  </span>
    </li>

   <nav>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
      <%= link_to "マイページ",customer_path(current_customer.id), class: 'btn btn-outline-secondary' %>
      </li>

      <li class="nav-item">
      <%= link_to "商品一覧",items_path, class: 'btn btn-outline-secondary' %>
      </li>

      <li class="nav-item">
      <%= link_to "カート",cart_items_path, class: 'btn btn-outline-secondary' %>
      </li>

      <li class="nav-item">
      <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-secondary' %>
      </li>
     </ul>
    </nav>

     <% elsif admin_signed_in? %>
     <div class= "admin-header">
     <div class= "admin-nav-bars">
     <nav class="nav navbar-nav">
      <span class="adjust"></span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
      <%= link_to "商品一覧",admin_items_path, class: 'btn btn-outline-secondary' %>
      </li>

      <li class="nav-item">
      <%= link_to "会員一覧", admin_customers_path, class: 'btn btn-outline-secondary' %>
      </li>

      <li class="nav-item">
      <%= link_to "注文履歴一覧", admin_root_path, class: 'btn btn-outline-secondary' %>
      </li>

      <li class="nav-item">
      <%= link_to "ログアウト",destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary' %>
      </li>
      </ul>
    </nav>
  </div>
  </div>

     <% else %>
      <li class="nav-item">
       <%= link_to "About", about_path, class: "btn btn-outline-secondary" %>
      </li>
       <li class="nav-item">
       <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary" %>
       </li>
       <li class="nav-item">
       <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary" %>
       </li>
       <li class="nav-item">
       <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-secondary" %>
       </li>
     <% end %>

      </ul>
      </div>
      </div>
      </nav>
    <%= yield %>
  </body>
</html>